baseURL = 'https://bmatho.com'
languageCode = 'en-us'
title = "Brendan's Blog"
theme = 'HermitV2'

[params.author]
 name = "Brendan Matheson" # Hi, It's Me!

[params]
 homeSubtitle = "Where personal learnings and homebrew blog posts come to meet!"
 homeSubtitlePrinter = false
 dateform = "Jan 2, 2006 03:04 PM"
 dateformShort = "Jan 2, 2006"
 dateformNumTime = "Jan 2, 2006 15:04"
 code_copy_button = true
 scrollToTop = true
 enableEmoji = true
 readTime = true
 shareSocial = true


[menu]

  [[menu.main]]
  name = "All Posts"
  url = "posts/"


[[params.socialLinks]]
    name = "github"
    url = "https://github.com/xBrendan66" # If you're reading this, you're already there!